"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const cors = require("cors");
const endpad_model_1 = require("endpad-model");
const CreateSession_1 = require("./resource/CreateSession");
const ConnectSession_1 = require("./resource/ConnectSession");
const UpdateSession_1 = require("./resource/UpdateSession");
const app = express();
app.use(express.json());
app.use(cors());
app.post(endpad_model_1.CreateSessionResource, CreateSession_1.createSessionHandler);
app.post(endpad_model_1.ConnectSessionResource, ConnectSession_1.connectSessionHandler);
app.post(endpad_model_1.UpdateSessionResource, UpdateSession_1.updateSessionHandler);
app.listen(3000);
